# 设置
[setting]
  # 域名信息获取网址，断点查询使用，即 domain 项
  url = ""
  # 查询结果保存网址
  # 比如 https://github.com/dutchcoders/transfer.sh 搭建的站点
  # 参数中带有 @，则会被替换成日期
  server_url = ""
  # 上传到指定服务器的鉴权信息
  # eg: username:password
  server_auth = ""
  # 本次查询域名列表保存文件名
  domain_flie = "domains.log"
  # 最大查询次数
  max_retries = 3
  # 日志级别
  # CRITICAL = 50
  # FATAL = CRITICAL
  # ERROR = 40
  # WARNING = 30
  # WARN = WARNING
  # INFO = 20
  # DEBUG = 10
  # NOTSET = 0
  log_level = 20
  # 日志目录
  log_dir = "logs"
  # 日志文件名
  log_file = "runtime.log"
  # result file
  result_file = "result.csv"

# 域名
[domain]
  # 后缀
  suffixes = "cn"
  # 长度
  length = 1
  # 组合模式
  # 1.纯数字，2.纯字母，3.纯数字+纯字母，4.数字与字母混合，5.自定义字符
  # 6.杂米（不含纯数字和字母），7.杂米，自定义字符
  mode = 3
  # 自定义组合字母表
  alphabets = ""
  # 起始域名（以此域名开始记录(含)，字符长度必须与 length 一致）
  start_char = ""
  # 组合前缀
  prefix = ""
  # 组合后缀
  suffix = ""
  # 是否已完成
  done = 0

# Whois
[whois]
  # 使用代理（功能未实现）
  proxy = false
  # 默认 Whois 提供商
  # west.西部数码(带注册时间),qcloud.腾讯云,zzidc.景安
  # 比如: west,qcloud,zzidc
  dnp = ""

# 通知
[notify]
  # 提供者，逗号分隔。如 feishu,dingtalk
  providers = ""

  # 钉钉
  [notify.dingtalk]
    # 钉钉 access_token
    token = ""
    # 钉钉 Secret
    secret = ""

  # 飞书
  [notify.feishu]
    # 飞书 Token
    token = ""
    # 飞书 Secret
    secret = ""

  # Lark
  [notify.lark]
    # Lark Token
    token = ""
    # Lark Secret
    secret = ""
