# This is a basic workflow to help you get started with Actions

name: "Find Domain"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
    inputs:
      domain:
        description: "Domain"
        default: ""
      domain_url:
        description: "Domain URL"
        default: ""

  # push:
    # branches: [ main ]
  # schedule:
  #   - cron: "*/40 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Working
        env:
          DOMAIN_INPUT: ${{ github.event.inputs.domain }}
          DOMAIN_URL_INPUT: ${{ github.event.inputs.domain_url }}
          FD_CONFIG_JSON: ${{ secrets.CONFIG_JSON}}
          FD_DOMAIN_URL: ${{ secrets.DOMAIN_URL}}
          FD_DOMAIN: ${{ secrets.DOMAIN }}
          FD_SERVER_URL: ${{ secrets.SERVER_URL}}
          FD_SERVER_AUTH: ${{ secrets.SERVER_AUTH}}
          FD_DNP: ${{ secrets.DNP}}
        run:
        - |
          if [ -n "$DOMAIN_INPUT" ]; then
            echo "FD_DOMAIN=$DOMAIN_INPUT" >> $GITHUB_ENV
          fi

          if [ -n "$DOMAIN_URL_INPUT" ]; then
            echo "FD_DOMAIN_URL=$DOMAIN_URL_INPUT" >> $GITHUB_ENV
          fi
        - |
          uv sync
          uv run findomain

      - name: Upload Domain Log
        uses: actions/upload-artifact@v4
        with:
          name: find-domain artifact
          path: logs
          retention-days: 3
